import { db } from "./db";
import { trails, campgrounds, marketplaceListings, users, activityLocations } from "@shared/schema";
import bcrypt from "bcrypt";

async function seed() {
  console.log("Seeding database...");

  const existingTrails = await db.select().from(trails);
  if (existingTrails.length > 0) {
    console.log("Database already seeded, skipping.");
    return;
  }

  const passwordHash = await bcrypt.hash("Demo@1234", 12);
  let demoUser;
  const existingUsers = await db.select().from(users);
  const existingDemo = existingUsers.find(u => u.email === "demo@verdara.com");
  if (existingDemo) {
    demoUser = existingDemo;
  } else {
    const [newUser] = await db.insert(users).values({
      firstName: "Trail",
      lastName: "Explorer",
      email: "demo@verdara.com",
      passwordHash,
      emailVerified: true,
      tier: "Pro Adventurer",
      trailsCompleted: 47,
      speciesIdentified: 156,
      conservationDonated: 250,
      equipmentTracked: 23,
    }).returning();
    demoUser = newUser;
  }

  await db.insert(trails).values([
    {
      name: "Cascade Ridge Loop",
      location: "Mt. Rainier National Park, WA",
      distance: "8.4 mi",
      elevation: "2,100 ft",
      difficulty: "Moderate",
      rating: 4.8,
      reviews: 342,
      image: "/images/cat-hiking.jpg",
      description: "A stunning loop trail featuring wildflower meadows, old-growth forest, and panoramic mountain views.",
      activityType: "hiking",
      features: ["Wildflowers", "Mountain Views", "Wildlife"],
      isFeatured: true,
      lat: 46.8523,
      lng: -121.7603,
    },
    {
      name: "Eagle Creek Trail",
      location: "Columbia River Gorge, OR",
      distance: "12.0 mi",
      elevation: "1,400 ft",
      difficulty: "Hard",
      rating: 4.9,
      reviews: 891,
      image: "/images/cat-camping.jpg",
      description: "Famous for Tunnel Falls and Punchbowl Falls. One of the most scenic hikes in the Pacific Northwest.",
      activityType: "hiking",
      features: ["Waterfalls", "River", "Old Growth"],
      isFeatured: true,
      lat: 45.6387,
      lng: -121.9197,
    },
    {
      name: "Rattlesnake Ledge",
      location: "North Bend, WA",
      distance: "4.0 mi",
      elevation: "1,160 ft",
      difficulty: "Easy",
      rating: 4.5,
      reviews: 1204,
      image: "/images/cat-rock-climbing.jpg",
      description: "Popular family-friendly hike with rewarding lake views from the ledge summit.",
      activityType: "hiking",
      features: ["Lake Views", "Family Friendly", "Dog Friendly"],
      isFeatured: true,
      lat: 47.4353,
      lng: -121.7714,
    },
    {
      name: "Enchantment Lakes",
      location: "Leavenworth, WA",
      distance: "18.0 mi",
      elevation: "4,400 ft",
      difficulty: "Expert",
      rating: 4.95,
      reviews: 567,
      image: "/images/cat-fishing.jpg",
      description: "Alpine wonderland with pristine lakes, golden larches, and mountain goats. Permit required.",
      activityType: "hiking",
      features: ["Alpine Lakes", "Permit Required", "Larch Trees"],
      isFeatured: true,
      lat: 47.5280,
      lng: -120.8220,
    },
    {
      name: "Tiger Mountain Trail",
      location: "Issaquah, WA",
      distance: "5.6 mi",
      elevation: "1,800 ft",
      difficulty: "Moderate",
      rating: 4.3,
      reviews: 456,
      image: "/images/cat-mountain-biking.jpg",
      description: "Well-maintained trail system popular with hikers and mountain bikers alike.",
      activityType: "mountain biking",
      features: ["Forest", "Multi-Use", "Year Round"],
      isFeatured: false,
      lat: 47.4743,
      lng: -122.0860,
    },
    {
      name: "Olympic Discovery Trail",
      location: "Olympic Peninsula, WA",
      distance: "15.2 mi",
      elevation: "800 ft",
      difficulty: "Easy",
      rating: 4.6,
      reviews: 289,
      image: "/images/cat-electric-mobility.jpg",
      description: "Paved multi-use path perfect for cycling, running, and electric mobility devices.",
      activityType: "cycling",
      features: ["Paved", "Coastal Views", "Accessible"],
      isFeatured: false,
      lat: 48.0765,
      lng: -123.4307,
    },
    {
      name: "Deception Pass State Park",
      location: "Whidbey Island, WA",
      distance: "3.8 mi",
      elevation: "600 ft",
      difficulty: "Easy",
      rating: 4.7,
      reviews: 723,
      image: "/images/cat-water-sports.jpg",
      description: "Iconic bridge views, tidepools, and old-growth forests on the rugged coastline.",
      activityType: "hiking",
      features: ["Bridge Views", "Tidepools", "Beach"],
      isFeatured: false,
      lat: 48.3935,
      lng: -122.6456,
    },
    {
      name: "Crystal Mountain Backcountry",
      location: "Crystal Mountain, WA",
      distance: "6.2 mi",
      elevation: "3,200 ft",
      difficulty: "Hard",
      rating: 4.4,
      reviews: 198,
      image: "/images/cat-winter-sports.jpg",
      description: "Challenging backcountry terrain with powder skiing and snowshoeing in winter months.",
      activityType: "winter sports",
      features: ["Backcountry", "Powder", "Avalanche Awareness"],
      isFeatured: false,
      lat: 46.9348,
      lng: -121.4742,
    },
  ]);

  await db.insert(campgrounds).values([
    {
      name: "Ohanapecosh Campground",
      location: "Mt. Rainier National Park, WA",
      price: 25,
      rating: 4.6,
      sites: 188,
      amenities: ["Flush Toilets", "Water", "Fire Rings", "Ranger Programs"],
      image: "/images/cat-camping.jpg",
      description: "Old-growth forest campground near hot springs and waterfalls.",
    },
    {
      name: "Sol Duc Hot Springs",
      location: "Olympic National Park, WA",
      price: 35,
      rating: 4.8,
      sites: 82,
      amenities: ["Hot Springs", "Flush Toilets", "Showers", "Store"],
      image: "/images/cat-hiking.jpg",
      description: "Resort campground with natural mineral hot springs and rainforest trails.",
    },
    {
      name: "Deception Pass State Park",
      location: "Whidbey Island, WA",
      price: 30,
      rating: 4.5,
      sites: 167,
      amenities: ["Flush Toilets", "Showers", "Beach Access", "Boat Launch"],
      image: "/images/cat-water-sports.jpg",
      description: "Coastal camping with stunning bridge views and tide pool exploration.",
    },
    {
      name: "Leavenworth KOA",
      location: "Leavenworth, WA",
      price: 45,
      rating: 4.3,
      sites: 120,
      amenities: ["Pool", "WiFi", "Store", "Playground", "Hot Tub"],
      image: "/images/cat-rock-climbing.jpg",
      description: "Full-service campground near Bavarian village and alpine trails.",
    },
  ]);

  await db.insert(marketplaceListings).values([
    {
      sellerId: demoUser.id,
      species: "Black Walnut",
      grade: "FAS Select",
      dimensions: "8/4 x 8\" x 10'",
      pricePerBf: 12.50,
      sellerName: "Pacific NW Timber",
      trustLevel: 4,
      trustScore: 945,
      location: "Portland, OR",
      image: "/images/cat-hunting.jpg",
      description: "Premium air-dried black walnut lumber. Stunning grain patterns, kiln-ready.",
    },
    {
      sellerId: demoUser.id,
      species: "Western Red Cedar",
      grade: "Clear Heart",
      dimensions: "4/4 x 6\" x 8'",
      pricePerBf: 8.75,
      sellerName: "Cascade Wood Supply",
      trustLevel: 3,
      trustScore: 872,
      location: "Seattle, WA",
      image: "/images/cat-camping.jpg",
      description: "Old-growth salvage cedar. Perfect for outdoor furniture and siding.",
    },
    {
      sellerId: demoUser.id,
      species: "Douglas Fir",
      grade: "#1 Common",
      dimensions: "6/4 x 10\" x 12'",
      pricePerBf: 5.25,
      sellerName: "Olympic Lumber Co",
      trustLevel: 2,
      trustScore: 720,
      location: "Olympia, WA",
      image: "/images/cat-fishing.jpg",
      description: "Structural-grade Douglas Fir timbers. Sustainably harvested.",
    },
    {
      sellerId: demoUser.id,
      species: "Bigleaf Maple",
      grade: "Figured/Quilted",
      dimensions: "8/4 x 12\" x 6'",
      pricePerBf: 18.00,
      sellerName: "Artisan Hardwoods NW",
      trustLevel: 4,
      trustScore: 960,
      location: "Eugene, OR",
      image: "/images/cat-mountain-biking.jpg",
      description: "Rare quilted maple with exceptional figure. Instrument and fine furniture grade.",
    },
    {
      sellerId: demoUser.id,
      species: "Oregon White Oak",
      grade: "FAS",
      dimensions: "4/4 x 8\" x 8'",
      pricePerBf: 9.50,
      sellerName: "Valley Oak Woodworks",
      trustLevel: 3,
      trustScore: 835,
      location: "Salem, OR",
      image: "/images/cat-electric-mobility.jpg",
      description: "Local white oak with beautiful grain. Wine barrel and cabinet grade.",
    },
  ]);

  console.log("Seeding complete!");
}

async function seedActivityLocations() {
  console.log("Checking activity_locations...");

  const existingLocations = await db.select().from(activityLocations);
  if (existingLocations.length > 0) {
    console.log("Activity locations already seeded, skipping.");
    return;
  }

  console.log("Seeding activity locations...");

  await db.insert(activityLocations).values([
    {
      type: "fishing",
      name: "Lake Fork Reservoir",
      location: "Lake Fork, TX",
      state: "Texas",
      description: "Premier trophy bass lake known for producing record largemouth bass. Over 27,000 acres of prime fishing waters with abundant structure and cover.",
      image: "/images/cat-fishing.jpg",
      rating: 4.9,
      reviews: 1842,
      difficulty: "Moderate",
      season: "Year-round, best March-June",
      regulations: "Slot limit 16-24 inches on largemouth bass. Daily bag limit 5. Valid TX fishing license required.",
      species: ["Largemouth Bass", "Crappie", "Channel Catfish", "Blue Catfish"],
      amenities: ["Boat Ramps", "Bait Shops", "Guide Services", "Campgrounds", "Fish Cleaning Stations"],
      tags: ["trophy bass", "reservoir", "boat fishing", "family friendly"],
      coordinates: { lat: 32.8818, lng: -95.5938 },
      metadata: { boat_access: "true", water_type: "freshwater", best_technique: "flipping and pitching" },
      isFeatured: true,
    },
    {
      type: "fishing",
      name: "Kenai River",
      location: "Cooper Landing, AK",
      state: "Alaska",
      description: "World-famous salmon river offering incredible runs of king, sockeye, and silver salmon. Crystal-clear turquoise waters flowing through stunning wilderness.",
      image: "/images/cat-water-sports.jpg",
      rating: 4.95,
      reviews: 2103,
      difficulty: "Moderate",
      season: "May-September",
      regulations: "Single-hook artificial lures only in certain sections. King salmon permits required. Check current ADF&G emergency orders.",
      species: ["King Salmon", "Sockeye Salmon", "Silver Salmon", "Rainbow Trout", "Dolly Varden"],
      amenities: ["Guide Services", "Drift Boat Access", "Campgrounds", "Lodges", "Fish Processing"],
      tags: ["salmon run", "fly fishing", "drift boat", "wilderness"],
      coordinates: { lat: 60.4900, lng: -149.8300 },
      metadata: { boat_access: "true", water_type: "freshwater river", best_technique: "drift fishing" },
      isFeatured: true,
    },
    {
      type: "fishing",
      name: "Chesapeake Bay",
      location: "Annapolis, MD",
      state: "Maryland",
      description: "The largest estuary in the US offering world-class striped bass fishing. Miles of shoreline, islands, and deep channels provide diverse angling opportunities.",
      image: "/images/cat-fishing.jpg",
      rating: 4.7,
      reviews: 1456,
      difficulty: "Easy",
      season: "April-November",
      regulations: "Striped bass minimum 19 inches. Seasonal closures apply. MD saltwater license required.",
      species: ["Striped Bass", "Blue Crab", "Bluefish", "Flounder", "White Perch"],
      amenities: ["Marinas", "Charter Boats", "Bait & Tackle Shops", "Restaurants", "Public Piers"],
      tags: ["saltwater", "charter fishing", "striped bass", "coastal"],
      coordinates: { lat: 38.9784, lng: -76.4922 },
      metadata: { boat_access: "true", water_type: "saltwater estuary", best_technique: "trolling" },
      isFeatured: false,
    },
    {
      type: "fishing",
      name: "Madison River",
      location: "Ennis, MT",
      state: "Montana",
      description: "Blue-ribbon trout stream flowing through pristine Montana valleys. Legendary dry fly fishing with prolific hatches and wild trout populations.",
      image: "/images/cat-camping.jpg",
      rating: 4.85,
      reviews: 987,
      difficulty: "Moderate",
      season: "June-October",
      regulations: "Catch and release in certain sections. Artificial lures only. MT fishing license required.",
      species: ["Brown Trout", "Rainbow Trout", "Mountain Whitefish"],
      amenities: ["Fly Shops", "Guide Services", "Wade Access Points", "Campgrounds"],
      tags: ["fly fishing", "trout stream", "wade fishing", "dry fly"],
      coordinates: { lat: 45.3469, lng: -111.7299 },
      metadata: { boat_access: "true", water_type: "freshwater river", best_technique: "dry fly" },
      isFeatured: true,
    },
    {
      type: "fishing",
      name: "Lake Okeechobee",
      location: "Clewiston, FL",
      state: "Florida",
      description: "Florida's inland sea spanning over 730 square miles. Exceptional bass fishing in vast grass flats, lily pads, and open water.",
      image: "/images/cat-water-sports.jpg",
      rating: 4.6,
      reviews: 1234,
      difficulty: "Easy",
      season: "Year-round, best September-April",
      regulations: "5 bass daily limit. No minimum size. Valid FL freshwater license required.",
      species: ["Largemouth Bass", "Black Crappie", "Bluegill", "Catfish"],
      amenities: ["Boat Ramps", "Marinas", "Guide Services", "RV Parks", "Bait Shops"],
      tags: ["bass fishing", "lake", "boat fishing", "trophy fish"],
      coordinates: { lat: 26.9467, lng: -80.8297 },
      metadata: { boat_access: "true", water_type: "freshwater lake", best_technique: "flipping grass" },
      isFeatured: false,
    },
    {
      type: "fishing",
      name: "Outer Banks Surf",
      location: "Nags Head, NC",
      state: "North Carolina",
      description: "Premier surf fishing destination along miles of undeveloped beaches. Excellent runs of red drum, bluefish, and flounder with beach driving access.",
      image: "/images/cat-fishing.jpg",
      rating: 4.5,
      reviews: 876,
      difficulty: "Moderate",
      season: "April-November",
      regulations: "Red drum slot 18-27 inches, 1 per day. NC coastal recreational fishing license required.",
      species: ["Red Drum", "Bluefish", "Flounder", "Speckled Trout", "Pompano"],
      amenities: ["Beach Access", "Tackle Shops", "4WD Beach Permits", "Campgrounds", "Pier Fishing"],
      tags: ["surf fishing", "beach", "red drum", "coastal"],
      coordinates: { lat: 35.9574, lng: -75.6241 },
      metadata: { boat_access: "false", water_type: "saltwater surf", best_technique: "surf casting" },
      isFeatured: false,
    },

    {
      type: "hunting",
      name: "Atchafalaya National Wildlife Refuge",
      location: "Krotz Springs, LA",
      state: "Louisiana",
      description: "Vast bottomland hardwood swamp ecosystem in the heart of the Atchafalaya Basin. Outstanding waterfowl hunting with flooded timber and marsh habitats.",
      image: "/images/cat-hunting.jpg",
      rating: 4.8,
      reviews: 654,
      difficulty: "Hard",
      season: "November-January (waterfowl), October-February (deer)",
      regulations: "Federal and state waterfowl stamps required. WMA permit needed. Steel shot only for waterfowl.",
      species: ["Mallard", "Wood Duck", "Teal", "White-tailed Deer", "Wild Turkey"],
      amenities: ["Boat Launches", "Public Blinds", "Campgrounds", "Check Stations"],
      tags: ["waterfowl", "swamp", "public land", "duck hunting"],
      coordinates: { lat: 30.5374, lng: -91.7429 },
      metadata: { land_type: "NWR", access_type: "boat", blind_type: "flooded timber" },
      isFeatured: true,
    },
    {
      type: "hunting",
      name: "Kaibab National Forest",
      location: "Fredonia, AZ",
      state: "Arizona",
      description: "North Kaibab unit renowned for trophy mule deer and elk hunting. Ponderosa pine and mixed conifer forests along the Grand Canyon's North Rim.",
      image: "/images/cat-hiking.jpg",
      rating: 4.85,
      reviews: 432,
      difficulty: "Hard",
      season: "October-November (rifle), August-September (archery)",
      regulations: "Draw-only tags for elk and mule deer. Hunter education required. Check unit-specific restrictions.",
      species: ["Mule Deer", "Elk", "Merriam's Turkey", "Mountain Lion"],
      amenities: ["Forest Roads", "Dispersed Camping", "Water Sources", "Trailheads"],
      tags: ["trophy mule deer", "elk", "national forest", "draw hunt"],
      coordinates: { lat: 36.7256, lng: -112.2166 },
      metadata: { land_type: "National Forest", access_type: "vehicle and foot", terrain: "mountainous" },
      isFeatured: true,
    },
    {
      type: "hunting",
      name: "Fort Stewart WMA",
      location: "Hinesville, GA",
      state: "Georgia",
      description: "Military installation with exceptional public hunting access on over 280,000 acres. Prime habitat for white-tailed deer, turkey, and small game.",
      image: "/images/cat-hunting.jpg",
      rating: 4.5,
      reviews: 567,
      difficulty: "Moderate",
      season: "September-February",
      regulations: "iSportsman registration required. Military installation access rules apply. GA hunting license and WMA stamp required.",
      species: ["White-tailed Deer", "Wild Turkey", "Feral Hog", "Dove", "Quail"],
      amenities: ["Managed Stands", "Check Stations", "Parking Areas", "Restrooms"],
      tags: ["WMA", "military land", "deer hunting", "public access"],
      coordinates: { lat: 31.8700, lng: -81.6100 },
      metadata: { land_type: "WMA/Military", access_type: "vehicle", registration: "iSportsman" },
      isFeatured: false,
    },
    {
      type: "hunting",
      name: "Theodore Roosevelt National Grasslands",
      location: "Dickinson, ND",
      state: "North Dakota",
      description: "Rolling mixed-grass prairies offering exceptional upland bird hunting. Miles of public grasslands with healthy populations of sharp-tailed grouse and pheasants.",
      image: "/images/cat-camping.jpg",
      rating: 4.6,
      reviews: 389,
      difficulty: "Moderate",
      season: "September-January",
      regulations: "ND small game license required. National Grassland hunting regulations apply. No lead shot for waterfowl.",
      species: ["Sharp-tailed Grouse", "Ring-necked Pheasant", "Hungarian Partridge", "Mule Deer", "Pronghorn"],
      amenities: ["Parking Areas", "Walk-in Access", "Campgrounds", "PLOTS Land Access"],
      tags: ["upland birds", "prairie", "public grassland", "walk-in hunting"],
      coordinates: { lat: 46.8967, lng: -103.5413 },
      metadata: { land_type: "National Grassland", access_type: "walk-in", terrain: "rolling prairie" },
      isFeatured: false,
    },
    {
      type: "hunting",
      name: "Black Hills National Forest",
      location: "Custer, SD",
      state: "South Dakota",
      description: "Mountainous pine forest in western South Dakota offering diverse big game hunting. Home to elk, mule deer, white-tailed deer, and mountain goats.",
      image: "/images/cat-hunting.jpg",
      rating: 4.7,
      reviews: 478,
      difficulty: "Hard",
      season: "September-November (archery and rifle)",
      regulations: "Draw tags for elk. Either-sex deer tags available OTC. SD hunting license required.",
      species: ["Elk", "Mule Deer", "White-tailed Deer", "Mountain Goat", "Merriam's Turkey"],
      amenities: ["Forest Roads", "Dispersed Camping", "Trailheads", "Water Sources", "Horse Camps"],
      tags: ["elk hunting", "national forest", "big game", "mountain hunting"],
      coordinates: { lat: 43.8554, lng: -103.4591 },
      metadata: { land_type: "National Forest", access_type: "vehicle and foot", terrain: "mountainous forest" },
      isFeatured: true,
    },
    {
      type: "hunting",
      name: "Green Swamp WMA",
      location: "Polk City, FL",
      state: "Florida",
      description: "Over 50,000 acres of cypress swamp and pine flatwoods in central Florida. Excellent deer, turkey, and hog hunting with year-round opportunities.",
      image: "/images/cat-hunting.jpg",
      rating: 4.4,
      reviews: 321,
      difficulty: "Moderate",
      season: "September-March",
      regulations: "FL hunting license and WMA permit required. Quota hunt permits for some seasons. Check area-specific rules.",
      species: ["White-tailed Deer", "Wild Turkey", "Feral Hog", "Osceola Turkey"],
      amenities: ["Check Stations", "Campgrounds", "ATV Trails", "Parking Areas"],
      tags: ["WMA", "swamp hunting", "hog hunting", "turkey hunting"],
      coordinates: { lat: 28.3800, lng: -81.9300 },
      metadata: { land_type: "WMA", access_type: "vehicle and ATV", terrain: "swamp and flatwoods" },
      isFeatured: false,
    },

    {
      type: "climbing",
      name: "Red River Gorge",
      location: "Slade, KY",
      state: "Kentucky",
      description: "World-class sport climbing destination with over 3,000 routes on stunning sandstone cliffs. Steep overhanging walls with incredible pocket pulling and technical face climbing.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.9,
      reviews: 2341,
      difficulty: "Moderate to Expert",
      season: "March-November, best in fall",
      regulations: "Respect fixed anchors. No new bolting without permission. Follow Leave No Trace principles. Some areas on private land require access fees.",
      species: ["Sport", "Trad", "Bouldering", "Top Rope"],
      amenities: ["Campgrounds", "Gear Shops", "Guide Services", "Restaurants", "Showers"],
      tags: ["sport climbing", "sandstone", "overhangs", "world class"],
      coordinates: { lat: 37.7750, lng: -83.6700 },
      metadata: { grade: "5.6-5.14d", rock_type: "sandstone", route_count: "3000+", style: "sport" },
      isFeatured: true,
    },
    {
      type: "climbing",
      name: "Joshua Tree National Park",
      location: "Twentynine Palms, CA",
      state: "California",
      description: "Iconic desert climbing on unique monzogranite formations. Thousands of routes ranging from beginner slabs to multi-pitch trad classics amid stunning desert landscape.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.85,
      reviews: 1987,
      difficulty: "Easy to Hard",
      season: "October-April",
      regulations: "National Park entrance fee required. No fixed anchors without NPS approval. Camping reservations needed in season.",
      species: ["Trad", "Sport", "Bouldering", "Top Rope", "Multi-pitch"],
      amenities: ["Campgrounds", "Visitor Center", "Guide Services", "Gear Rental"],
      tags: ["trad climbing", "desert", "monzogranite", "multi-pitch"],
      coordinates: { lat: 33.8734, lng: -115.9010 },
      metadata: { grade: "5.0-5.13", rock_type: "monzogranite", route_count: "8000+", style: "trad" },
      isFeatured: true,
    },
    {
      type: "climbing",
      name: "Hueco Tanks State Park",
      location: "El Paso, TX",
      state: "Texas",
      description: "Legendary bouldering destination featuring world-class problems on syenite rock. Home to iconic problems and pictograph-covered caves in the Chihuahuan Desert.",
      image: "/images/cat-climbing.jpg",
      rating: 4.8,
      reviews: 1245,
      difficulty: "Moderate to Expert",
      season: "October-March",
      regulations: "Daily visitor limits enforced. Reservations required. Guide required for North Mountain. No chalk on pictographs.",
      species: ["Bouldering", "Sport", "Top Rope"],
      amenities: ["Campgrounds", "Restrooms", "Guide Services", "Water Stations"],
      tags: ["bouldering", "syenite", "desert", "world class"],
      coordinates: { lat: 31.9191, lng: -106.0411 },
      metadata: { grade: "V0-V15", rock_type: "syenite", route_count: "2000+", style: "bouldering" },
      isFeatured: true,
    },
    {
      type: "climbing",
      name: "Rumney Rocks",
      location: "Rumney, NH",
      state: "New Hampshire",
      description: "Premier sport climbing crag in New England with over 300 routes on metamorphic schist. Excellent variety from beginner-friendly to cutting-edge difficulty.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.7,
      reviews: 876,
      difficulty: "Easy to Hard",
      season: "April-November",
      regulations: "Stay on marked trails. No new routes without Rumney Climbers Association approval. Dogs must be leashed.",
      species: ["Sport", "Top Rope"],
      amenities: ["Parking", "Trail Access", "Nearby Camping", "Gear Shops"],
      tags: ["sport climbing", "schist", "new england", "beginner friendly"],
      coordinates: { lat: 43.8052, lng: -71.8125 },
      metadata: { grade: "5.4-5.14b", rock_type: "schist", route_count: "300+", style: "sport" },
      isFeatured: false,
    },
    {
      type: "climbing",
      name: "Smith Rock State Park",
      location: "Terrebonne, OR",
      state: "Oregon",
      description: "Birthplace of American sport climbing with iconic routes on welded tuff and basalt towers. Stunning Crooked River canyon setting with hundreds of classic lines.",
      image: "/images/cat-climbing.jpg",
      rating: 4.9,
      reviews: 1654,
      difficulty: "Easy to Expert",
      season: "March-November, best spring and fall",
      regulations: "State park day-use fee required. Bivouac camping area available. Dogs must be leashed. Seasonal raptor closures.",
      species: ["Sport", "Trad", "Multi-pitch", "Bouldering"],
      amenities: ["Campground", "Restrooms", "Water", "Trails", "Guide Services"],
      tags: ["sport climbing", "tuff", "classic routes", "birthplace of sport climbing"],
      coordinates: { lat: 44.3682, lng: -121.1426 },
      metadata: { grade: "5.5-5.14c", rock_type: "welded tuff", route_count: "1800+", style: "sport and trad" },
      isFeatured: false,
    },
    {
      type: "climbing",
      name: "New River Gorge",
      location: "Fayetteville, WV",
      state: "West Virginia",
      description: "East Coast climbing mecca with over 1,700 routes on bullet-hard Nuttall Sandstone. Steep, athletic climbing with incredible exposure above the New River.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.85,
      reviews: 1432,
      difficulty: "Moderate to Expert",
      season: "March-November",
      regulations: "National Park and Preserve rules apply. Some areas require approach from designated trails. Leave No Trace principles.",
      species: ["Sport", "Trad", "Bouldering", "Top Rope"],
      amenities: ["Campgrounds", "Gear Shops", "Guide Services", "Restaurants", "Visitor Center"],
      tags: ["sport climbing", "trad climbing", "sandstone", "national park"],
      coordinates: { lat: 38.0659, lng: -81.0787 },
      metadata: { grade: "5.5-5.14a", rock_type: "Nuttall sandstone", route_count: "1700+", style: "sport and trad" },
      isFeatured: false,
    },

    {
      type: "public_lands",
      name: "Yellowstone National Park",
      location: "Yellowstone, WY",
      state: "Wyoming",
      description: "America's first national park spanning over 2.2 million acres of geothermal wonders, wildlife, and pristine wilderness. Home to Old Faithful, Grand Prismatic Spring, and the largest concentration of geysers on Earth.",
      image: "/images/cat-hiking.jpg",
      rating: 4.9,
      reviews: 12453,
      difficulty: null,
      season: "Year-round, some roads closed November-April",
      regulations: "NPS entrance fee required. Backcountry permits for overnight stays. Stay 100 yards from bears and wolves, 25 yards from other wildlife.",
      species: null,
      amenities: ["Visitor Centers", "Campgrounds", "Lodges", "Restaurants", "General Stores", "Ranger Programs", "Shuttle Service"],
      tags: ["national park", "geysers", "wildlife", "wilderness", "iconic"],
      coordinates: { lat: 44.4280, lng: -110.5885 },
      metadata: { designation: "National Park", acreage: "2219791", established: "1872", managing_agency: "NPS" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Boundary Waters Canoe Area Wilderness",
      location: "Ely, MN",
      state: "Minnesota",
      description: "Over one million acres of pristine lakes, rivers, and boreal forest along the Canadian border. Premier paddling and fishing destination with over 1,200 miles of canoe routes.",
      image: "/images/cat-water-sports.jpg",
      rating: 4.85,
      reviews: 4321,
      difficulty: null,
      season: "May-September for paddling, year-round access",
      regulations: "Wilderness permits required May-September. Group size limits. No motors in most areas. Bear canisters required.",
      species: null,
      amenities: ["Entry Points", "Portage Trails", "Designated Campsites", "Outfitters", "Ranger Stations"],
      tags: ["wilderness", "canoeing", "fishing", "boreal forest", "pristine"],
      coordinates: { lat: 48.0833, lng: -91.8333 },
      metadata: { designation: "Wilderness Area", acreage: "1090000", established: "1978", managing_agency: "USFS" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Custer Gallatin National Forest",
      location: "Bozeman, MT",
      state: "Montana",
      description: "3.1 million acres of diverse landscapes from alpine peaks to rolling grasslands. Gateway to Yellowstone with exceptional hiking, fishing, hunting, and winter recreation.",
      image: "/images/cat-camping.jpg",
      rating: 4.7,
      reviews: 2876,
      difficulty: null,
      season: "Year-round",
      regulations: "Forest Service regulations apply. Campfire permits may be required. Check current fire restrictions. Some trails require stock use permits.",
      species: null,
      amenities: ["Campgrounds", "Trailheads", "Ranger Stations", "Boat Ramps", "Picnic Areas", "Horse Camps"],
      tags: ["national forest", "hiking", "fishing", "hunting", "mountain recreation"],
      coordinates: { lat: 45.6833, lng: -110.4000 },
      metadata: { designation: "National Forest", acreage: "3100000", established: "2014", managing_agency: "USFS" },
      isFeatured: false,
    },
    {
      type: "public_lands",
      name: "Grand Staircase-Escalante National Monument",
      location: "Escalante, UT",
      state: "Utah",
      description: "Nearly 1.9 million acres of rugged canyon country with slot canyons, natural bridges, and vast wilderness. One of the last places in the continental US to be mapped.",
      image: "/images/cat-hiking.jpg",
      rating: 4.8,
      reviews: 3456,
      difficulty: null,
      season: "March-November, avoid summer heat",
      regulations: "BLM permit required for overnight backpacking in certain areas. High-clearance vehicles recommended. Check road conditions before travel.",
      species: null,
      amenities: ["Visitor Centers", "Dispersed Camping", "Trailheads", "Scenic Drives"],
      tags: ["BLM", "canyon country", "slot canyons", "wilderness", "remote"],
      coordinates: { lat: 37.3861, lng: -111.4356 },
      metadata: { designation: "National Monument (BLM)", acreage: "1870000", established: "1996", managing_agency: "BLM" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Adirondack Park",
      location: "Lake Placid, NY",
      state: "New York",
      description: "The largest publicly protected area in the contiguous US at 6 million acres. Mix of public and private land featuring 46 High Peaks, thousands of lakes, and vast forests.",
      image: "/images/cat-mountain-biking.jpg",
      rating: 4.75,
      reviews: 5678,
      difficulty: null,
      season: "Year-round",
      regulations: "DEC regulations apply. Bear canisters required in Eastern High Peaks. Permits for some trailheads during peak season.",
      species: null,
      amenities: ["Campgrounds", "Lean-tos", "Visitor Centers", "Boat Launches", "Ski Areas", "Trailheads"],
      tags: ["state park", "high peaks", "lakes", "four season", "hiking"],
      coordinates: { lat: 44.1126, lng: -74.0404 },
      metadata: { designation: "State Park/Forest Preserve", acreage: "6100000", established: "1892", managing_agency: "NYS DEC" },
      isFeatured: false,
    },
    {
      type: "public_lands",
      name: "Ocala National Forest",
      location: "Silver Springs, FL",
      state: "Florida",
      description: "The southernmost national forest in the continental US featuring sand pine scrub, freshwater springs, and subtropical wilderness. Year-round recreation in a unique ecosystem.",
      image: "/images/cat-electric-mobility.jpg",
      rating: 4.5,
      reviews: 2134,
      difficulty: null,
      season: "Year-round, best October-April",
      regulations: "Forest Service regulations. Campfire permits required. Swimming at own risk at springs. OHV permits for designated trails.",
      species: null,
      amenities: ["Campgrounds", "Springs", "Swimming Areas", "OHV Trails", "Boat Ramps", "Picnic Areas"],
      tags: ["national forest", "springs", "subtropical", "OHV", "swimming"],
      coordinates: { lat: 29.1900, lng: -81.6500 },
      metadata: { designation: "National Forest", acreage: "607000", established: "1908", managing_agency: "USFS" },
      isFeatured: false,
    },
    {
      type: "public_lands",
      name: "Big Bend National Park",
      location: "Big Bend, TX",
      state: "Texas",
      description: "Over 800,000 acres of Chihuahuan Desert wilderness along the Rio Grande. Dramatic canyons, desert mountains, and some of the darkest night skies in North America.",
      image: "/images/cat-winter-sports.jpg",
      rating: 4.8,
      reviews: 3890,
      difficulty: null,
      season: "October-April, summers extremely hot",
      regulations: "NPS entrance fee. Backcountry permits required. No collecting rocks, plants, or artifacts. Border crossing restrictions.",
      species: null,
      amenities: ["Visitor Centers", "Campgrounds", "Lodge", "River Access", "Hot Springs", "Ranger Programs"],
      tags: ["national park", "desert", "dark skies", "river", "remote"],
      coordinates: { lat: 29.2498, lng: -103.2502 },
      metadata: { designation: "National Park", acreage: "801163", established: "1944", managing_agency: "NPS" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Pisgah National Forest",
      location: "Brevard, NC",
      state: "North Carolina",
      description: "Over 500,000 acres of lush Appalachian forest with stunning waterfalls, the Blue Ridge Parkway, and legendary mountain biking trails. Birthplace of modern forestry in America.",
      image: "/images/cat-mountain-biking.jpg",
      rating: 4.7,
      reviews: 3210,
      difficulty: null,
      season: "Year-round",
      regulations: "Forest Service regulations apply. Hunting in designated areas with valid license. Campfire restrictions during dry periods.",
      species: null,
      amenities: ["Campgrounds", "Trailheads", "Waterfalls", "Swimming Holes", "Mountain Biking Trails", "Ranger Station"],
      tags: ["national forest", "waterfalls", "mountain biking", "appalachian", "forestry"],
      coordinates: { lat: 35.3167, lng: -82.7333 },
      metadata: { designation: "National Forest", acreage: "512758", established: "1916", managing_agency: "USFS" },
      isFeatured: false,
    },

    {
      type: "mtb",
      name: "Whistler Mountain Bike Park",
      location: "Whistler, BC",
      state: "British Columbia",
      description: "The undisputed king of lift-accessed mountain biking with over 70 trails spanning 4,900 feet of vertical. From flowy beginner runs to gnarly expert-only lines, Whistler defines gravity riding.",
      image: "/images/cat-mtb.jpg",
      rating: 4.95,
      reviews: 3421,
      difficulty: "Easy to Expert",
      season: "May-October",
      regulations: "Full-face helmet required on all trails. Bike park pass required. Protective gear strongly recommended. Trail closures during maintenance.",
      species: ["Downhill", "Enduro", "Flow Trail", "Jump Line"],
      amenities: ["Bike Rentals", "Repair Shops", "Lift Access", "Lessons", "Restaurants", "Pro Shops"],
      tags: ["bike park", "lift served", "downhill", "world class"],
      coordinates: { lat: 50.1163, lng: -122.9574 },
      metadata: { trail_count: "70+", trail_surface: "machine built and natural", lift_served: "true" },
      isFeatured: true,
    },
    {
      type: "mtb",
      name: "Whole Enchilada Trail System",
      location: "Moab, UT",
      state: "Utah",
      description: "Epic 26-mile point-to-point ride descending from alpine forests to desert slickrock. Traverses five distinct ecosystems with technical terrain and breathtaking canyon views.",
      image: "/images/cat-mtb.jpg",
      rating: 4.9,
      reviews: 2187,
      difficulty: "Hard",
      season: "April-October",
      regulations: "Shuttle required for full ride. Stay on designated trails to protect cryptobiotic soil. BLM and Forest Service rules apply.",
      species: ["Enduro", "Cross-Country", "All-Mountain"],
      amenities: ["Shuttle Services", "Bike Shops", "Campgrounds", "Guide Services"],
      tags: ["epic ride", "desert", "slickrock", "point to point"],
      coordinates: { lat: 38.5733, lng: -109.5498 },
      metadata: { trail_count: "15+", trail_surface: "slickrock and singletrack", lift_served: "false" },
      isFeatured: true,
    },
    {
      type: "mtb",
      name: "Slaughter Pen & Coler Trail Systems",
      location: "Bentonville, AR",
      state: "Arkansas",
      description: "World-class purpose-built trail network funded by the Walton family. Over 130 miles of impeccably maintained singletrack with progressive features and flow trails for all abilities.",
      image: "/images/cat-mtb.jpg",
      rating: 4.85,
      reviews: 1876,
      difficulty: "Easy to Hard",
      season: "Year-round",
      regulations: "Free trail access. Yield to uphill riders. No e-bikes on natural surface trails without posted permission. Trails close during wet conditions.",
      species: ["Cross-Country", "Flow Trail", "Enduro", "Jump Line"],
      amenities: ["Bike Shops", "Trail Centers", "Restaurants", "Pump Tracks", "Skills Parks"],
      tags: ["purpose built", "flow trails", "family friendly", "mountain biking capital"],
      coordinates: { lat: 36.3729, lng: -94.2088 },
      metadata: { trail_count: "130+", trail_surface: "machine built", lift_served: "false" },
      isFeatured: false,
    },
    {
      type: "mtb",
      name: "Kingdom Trails",
      location: "East Burke, VT",
      state: "Vermont",
      description: "Over 100 miles of singletrack winding through the pastoral Northeast Kingdom. A community-built trail network on private land featuring flowy cross-country loops and technical descents.",
      image: "/images/cat-mtb.jpg",
      rating: 4.8,
      reviews: 1432,
      difficulty: "Easy to Hard",
      season: "May-October",
      regulations: "Day pass or membership required. Respect private landowners. Trails may close during mud season. Dogs allowed on leash.",
      species: ["Cross-Country", "Enduro", "Flow Trail"],
      amenities: ["Trail Center", "Bike Rentals", "Lessons", "Campgrounds", "General Store"],
      tags: ["cross country", "new england", "community trails", "scenic"],
      coordinates: { lat: 44.5912, lng: -71.9470 },
      metadata: { trail_count: "100+", trail_surface: "natural singletrack", lift_served: "false" },
      isFeatured: false,
    },
    {
      type: "mtb",
      name: "Pisgah Mountain Bike Trails",
      location: "Brevard, NC",
      state: "North Carolina",
      description: "Raw, technical old-school mountain biking through dense Appalachian forest. Rooty, rocky singletrack with significant climbing and fast descents along creeks and ridgelines.",
      image: "/images/cat-mtb.jpg",
      rating: 4.75,
      reviews: 1654,
      difficulty: "Hard to Expert",
      season: "Year-round, best spring and fall",
      regulations: "Forest Service regulations apply. Some trails shared with hikers. No riding during active logging operations. Stay on marked trails.",
      species: ["Enduro", "Cross-Country", "All-Mountain", "Downhill"],
      amenities: ["Campgrounds", "Bike Shops", "Shuttle Services", "Swimming Holes"],
      tags: ["technical", "old school", "appalachian", "rooty"],
      coordinates: { lat: 35.2884, lng: -82.7460 },
      metadata: { trail_count: "80+", trail_surface: "natural technical", lift_served: "false" },
      isFeatured: false,
    },

    {
      type: "camping",
      name: "Mather Campground",
      location: "Grand Canyon Village, AZ",
      state: "Arizona",
      description: "The premier South Rim campground set among pinyon and juniper trees just steps from the canyon rim. Wake up to stunning sunrises over one of the world's most iconic landscapes.",
      image: "/images/cat-camping.jpg",
      rating: 4.7,
      reviews: 4532,
      difficulty: null,
      season: "Year-round",
      regulations: "Reservations required March-November. 7-night stay limit. Quiet hours 10pm-6am. Food must be stored in provided lockers. Generators allowed limited hours.",
      species: null,
      amenities: ["Flush Toilets", "Showers", "Laundry", "General Store", "Shuttle Stop", "Dump Station"],
      tags: ["national park", "south rim", "family friendly", "iconic"],
      coordinates: { lat: 36.0544, lng: -112.1401 },
      metadata: { site_count: "319", hookups: "none", reservable: "true" },
      isFeatured: true,
    },
    {
      type: "camping",
      name: "Upper Pines Campground",
      location: "Yosemite Valley, CA",
      state: "California",
      description: "The largest campground in Yosemite Valley nestled among towering ponderosa pines. Walking distance to Half Dome trailhead, Vernal and Nevada Falls, and the iconic valley views.",
      image: "/images/cat-camping.jpg",
      rating: 4.6,
      reviews: 5876,
      difficulty: null,
      season: "March-November",
      regulations: "Reservations required up to 5 months in advance. Bear canisters required. 14-night stay limit. Quiet hours enforced. Campfires in fire rings only.",
      species: null,
      amenities: ["Flush Toilets", "Showers", "Dump Station", "Shuttle Access", "Bear Lockers"],
      tags: ["national park", "yosemite valley", "iconic", "reservable"],
      coordinates: { lat: 37.7373, lng: -119.5633 },
      metadata: { site_count: "238", hookups: "none", reservable: "true" },
      isFeatured: true,
    },
    {
      type: "camping",
      name: "Assateague Island National Seashore",
      location: "Berlin, MD",
      state: "Maryland",
      description: "Beachfront camping on a pristine barrier island famous for its wild horses. Fall asleep to the sound of ocean waves and wake to wild ponies grazing near your tent.",
      image: "/images/cat-camping.jpg",
      rating: 4.8,
      reviews: 2345,
      difficulty: null,
      season: "Year-round",
      regulations: "Reservations recommended. All food must be stored in hard-sided containers. No feeding wild horses. Insect repellent strongly recommended spring-fall.",
      species: null,
      amenities: ["Chemical Toilets", "Cold Water Showers", "Beach Access", "Kayak Launch", "Visitor Center"],
      tags: ["beach camping", "wild horses", "barrier island", "unique"],
      coordinates: { lat: 38.2169, lng: -75.1552 },
      metadata: { site_count: "104", hookups: "none", reservable: "true" },
      isFeatured: false,
    },
    {
      type: "camping",
      name: "Kirk Creek Campground",
      location: "Big Sur, CA",
      state: "California",
      description: "Spectacular clifftop camping perched 100 feet above the Pacific Ocean along Highway 1. Arguably the most scenic campground on the West Coast with unobstructed ocean and sunset views.",
      image: "/images/cat-camping.jpg",
      rating: 4.85,
      reviews: 1987,
      difficulty: null,
      season: "Year-round, weather permitting",
      regulations: "First-come first-served and reservable sites. 14-day stay limit. Campfires in fire rings only when permitted. Highway 1 closures possible during storms.",
      species: null,
      amenities: ["Vault Toilets", "Picnic Tables", "Fire Rings", "Beach Access Trail"],
      tags: ["ocean views", "big sur", "scenic", "clifftop"],
      coordinates: { lat: 35.9848, lng: -121.4931 },
      metadata: { site_count: "33", hookups: "none", reservable: "true" },
      isFeatured: false,
    },
    {
      type: "camping",
      name: "Boundary Waters Entry Point - Lake One",
      location: "Ely, MN",
      state: "Minnesota",
      description: "Gateway to the Boundary Waters Canoe Area Wilderness with paddle-in campsites on pristine boreal lakes. True wilderness camping under some of the darkest skies in the eastern US.",
      image: "/images/cat-camping.jpg",
      rating: 4.9,
      reviews: 1654,
      difficulty: "Moderate",
      season: "May-September",
      regulations: "Wilderness permit required. Group size limited to 9. No cans or bottles. Bear-proof food storage required. Campfires in designated grates only.",
      species: null,
      amenities: ["Canoe Outfitters", "Portage Trails", "Designated Fire Grates", "Wilderness Latrines"],
      tags: ["wilderness", "canoe camping", "remote", "dark skies"],
      coordinates: { lat: 47.9167, lng: -91.5000 },
      metadata: { site_count: "backcountry", hookups: "none", reservable: "true" },
      isFeatured: false,
    },

    {
      type: "emobility",
      name: "Tahoe Rim Trail E-Bike Routes",
      location: "Incline Village, NV",
      state: "Nevada",
      description: "Select sections of the iconic Tahoe Rim Trail open to Class 1 e-bikes with stunning alpine lake views. Smooth singletrack and fire roads winding through pine forests above the sapphire waters of Lake Tahoe.",
      image: "/images/cat-emobility.jpg",
      rating: 4.7,
      reviews: 876,
      difficulty: "Moderate",
      season: "June-October",
      regulations: "Class 1 e-bikes only on designated multi-use trails. No e-bikes in wilderness areas. Stay on marked trails. Speed limit 15 mph on shared paths.",
      species: ["E-Bike", "E-Mountain Bike"],
      amenities: ["Charging Stations", "Bike Shops", "E-Bike Rentals", "Trailhead Parking", "Restaurants"],
      tags: ["e-bike", "alpine", "lake views", "scenic"],
      coordinates: { lat: 39.2533, lng: -119.9528 },
      metadata: { charging_stations: "3", trail_surface: "singletrack and fire road", range_friendly: "true" },
      isFeatured: true,
    },
    {
      type: "emobility",
      name: "Bentonville E-Bike Network",
      location: "Bentonville, AR",
      state: "Arkansas",
      description: "Extensive paved and gravel greenway network connecting trails, restaurants, and attractions throughout Northwest Arkansas. Purpose-built infrastructure with dedicated e-bike charging stations.",
      image: "/images/cat-emobility.jpg",
      rating: 4.8,
      reviews: 1234,
      difficulty: "Easy",
      season: "Year-round",
      regulations: "E-bikes allowed on all paved greenways. Class 1 only on natural surface trails where posted. Speed limit 20 mph on shared paths. Yield to pedestrians.",
      species: ["E-Bike", "Onewheel", "Electric Scooter"],
      amenities: ["Charging Stations", "E-Bike Rentals", "Repair Stations", "Restaurants", "Rest Areas"],
      tags: ["e-bike", "greenway", "family friendly", "infrastructure"],
      coordinates: { lat: 36.3729, lng: -94.2088 },
      metadata: { charging_stations: "12", trail_surface: "paved and gravel", range_friendly: "true" },
      isFeatured: true,
    },
    {
      type: "emobility",
      name: "Moab E-Bike Adventures",
      location: "Moab, UT",
      state: "Utah",
      description: "Experience the red rock desert on electric-assist bikes with access to scenic roads and select trails. E-bikes open up the stunning canyon country to riders of all fitness levels.",
      image: "/images/cat-emobility.jpg",
      rating: 4.6,
      reviews: 765,
      difficulty: "Easy to Moderate",
      season: "March-November",
      regulations: "E-bikes allowed on roads and designated trails only. No e-bikes on singletrack trails in most BLM areas. Check current e-bike policy before riding.",
      species: ["E-Bike", "E-Mountain Bike"],
      amenities: ["E-Bike Rentals", "Guide Services", "Bike Shops", "Campgrounds"],
      tags: ["e-bike", "desert", "scenic", "red rock"],
      coordinates: { lat: 38.5733, lng: -109.5498 },
      metadata: { charging_stations: "4", trail_surface: "paved and gravel roads", range_friendly: "true" },
      isFeatured: false,
    },
    {
      type: "emobility",
      name: "Burke-Gilman Trail",
      location: "Seattle, WA",
      state: "Washington",
      description: "27-mile paved multi-use trail connecting neighborhoods, parks, and the University of Washington. A premier urban e-bike commuting and recreation corridor along Lake Washington and Lake Union.",
      image: "/images/cat-emobility.jpg",
      rating: 4.5,
      reviews: 2341,
      difficulty: "Easy",
      season: "Year-round",
      regulations: "All e-bike classes permitted. Speed limit 15 mph. Yield to pedestrians. Use bell or voice when passing. Lights required at night.",
      species: ["E-Bike", "Onewheel", "EUC", "Electric Scooter"],
      amenities: ["Bike Shops", "Restaurants", "Parks", "Transit Connections", "Restrooms"],
      tags: ["urban trail", "commuter", "paved", "scenic"],
      coordinates: { lat: 47.6588, lng: -122.3426 },
      metadata: { charging_stations: "6", trail_surface: "paved", range_friendly: "true" },
      isFeatured: false,
    },
    {
      type: "emobility",
      name: "Katy Trail State Park",
      location: "Boonville, MO",
      state: "Missouri",
      description: "The longest rail-trail in America stretching 240 miles along the Missouri River. Crushed limestone surface ideal for e-bikes with gentle grades, charming small towns, and river bluff scenery.",
      image: "/images/cat-emobility.jpg",
      rating: 4.65,
      reviews: 1567,
      difficulty: "Easy",
      season: "Year-round, best spring and fall",
      regulations: "E-bikes allowed on entire trail. Speed limit 15 mph. Yield to pedestrians and equestrians. Trail closed during flooding events.",
      species: ["E-Bike", "E-Trike"],
      amenities: ["Trailhead Parking", "B&Bs", "Restaurants", "Camping", "Bike Shuttle Services"],
      tags: ["rail trail", "long distance", "river views", "small towns"],
      coordinates: { lat: 38.9762, lng: -92.7438 },
      metadata: { charging_stations: "8", trail_surface: "crushed limestone", range_friendly: "true" },
      isFeatured: false,
    },

    {
      type: "winter",
      name: "Jackson Hole Mountain Resort",
      location: "Teton Village, WY",
      state: "Wyoming",
      description: "Legendary steep terrain with 4,139 feet of continuous vertical drop and access to expert chutes, bowls, and backcountry gates. Consistently rated among the top ski resorts in North America.",
      image: "/images/cat-winter.jpg",
      rating: 4.9,
      reviews: 4567,
      difficulty: "Hard to Expert",
      season: "December-April",
      regulations: "Lift ticket or season pass required. Avalanche awareness training recommended for backcountry gates. Helmet strongly recommended. Uphill travel policy in effect.",
      species: ["Alpine Skiing", "Snowboarding", "Backcountry Skiing"],
      amenities: ["Lifts", "Ski School", "Rentals", "Lodges", "Restaurants", "Village", "Terrain Parks"],
      tags: ["expert terrain", "steep", "backcountry", "iconic"],
      coordinates: { lat: 43.5877, lng: -110.8279 },
      metadata: { vertical_drop: "4139 ft", annual_snowfall: "459 inches", lifts: "13" },
      isFeatured: true,
    },
    {
      type: "winter",
      name: "Stowe Mountain Resort",
      location: "Stowe, VT",
      state: "Vermont",
      description: "The historic ski capital of the East with classic New England charm and challenging terrain on Mt. Mansfield, Vermont's highest peak. Legendary narrow trails and glades through hardwood forests.",
      image: "/images/cat-winter.jpg",
      rating: 4.8,
      reviews: 3245,
      difficulty: "Moderate to Expert",
      season: "November-April",
      regulations: "Lift ticket or Ikon Pass required. Terrain park rules posted at entry. Uphill travel on designated routes only. Ski patrol authority in all areas.",
      species: ["Alpine Skiing", "Snowboarding", "Nordic", "Snowshoeing"],
      amenities: ["Lifts", "Ski School", "Rentals", "Spa", "Village", "Cross-Country Center", "Terrain Parks"],
      tags: ["new england", "classic", "historic", "challenging"],
      coordinates: { lat: 44.5303, lng: -72.7814 },
      metadata: { vertical_drop: "2160 ft", annual_snowfall: "314 inches", lifts: "13" },
      isFeatured: true,
    },
    {
      type: "winter",
      name: "Telluride Ski Resort",
      location: "Telluride, CO",
      state: "Colorado",
      description: "Stunning box canyon setting with world-class skiing and a charming historic mining town. Free gondola connects town to Mountain Village with terrain for all abilities and incredible views.",
      image: "/images/cat-winter.jpg",
      rating: 4.85,
      reviews: 2876,
      difficulty: "Moderate to Expert",
      season: "November-April",
      regulations: "Lift ticket or Ikon Pass required. Free gondola operates year-round. Backcountry access gates require avalanche gear. Slow skiing zones enforced.",
      species: ["Alpine Skiing", "Snowboarding", "Nordic", "Snowshoeing"],
      amenities: ["Lifts", "Free Gondola", "Ski School", "Rentals", "Restaurants", "Historic Town", "Spa"],
      tags: ["scenic", "historic town", "box canyon", "diverse terrain"],
      coordinates: { lat: 37.9375, lng: -107.8123 },
      metadata: { vertical_drop: "4425 ft", annual_snowfall: "309 inches", lifts: "18" },
      isFeatured: false,
    },
    {
      type: "winter",
      name: "Mt. Baker Ski Area",
      location: "Glacier, WA",
      state: "Washington",
      description: "Holds the world record for most snowfall in a single season at 1,140 inches. No-frills ski area known for deep powder, steep terrain, and a passionate local community.",
      image: "/images/cat-winter.jpg",
      rating: 4.7,
      reviews: 1987,
      difficulty: "Moderate to Hard",
      season: "November-April",
      regulations: "Day tickets only, no reservations needed. Chains required on access road during storms. No overnight parking. Backcountry travel at own risk.",
      species: ["Alpine Skiing", "Snowboarding", "Backcountry Skiing", "Snowshoeing"],
      amenities: ["Lifts", "Rentals", "Lodge", "Cafeteria", "Ski School"],
      tags: ["powder", "deep snow", "no frills", "local favorite"],
      coordinates: { lat: 48.8571, lng: -121.6637 },
      metadata: { vertical_drop: "1500 ft", annual_snowfall: "641 inches", lifts: "10" },
      isFeatured: false,
    },
    {
      type: "winter",
      name: "Bretton Woods Mountain Resort",
      location: "Bretton Woods, NH",
      state: "New Hampshire",
      description: "New Hampshire's largest ski area set against the stunning backdrop of Mt. Washington and the Presidential Range. Family-friendly resort with excellent grooming and extensive Nordic trail system.",
      image: "/images/cat-winter.jpg",
      rating: 4.6,
      reviews: 1654,
      difficulty: "Easy to Moderate",
      season: "November-April",
      regulations: "Lift ticket or season pass required. Nordic trail pass separate. Snowshoe trails marked and maintained. Uphill policy posted at base area.",
      species: ["Alpine Skiing", "Nordic", "Snowshoeing", "Fat Biking"],
      amenities: ["Lifts", "Ski School", "Rentals", "Nordic Center", "Canopy Tour", "Restaurants", "Hotel"],
      tags: ["family friendly", "nordic", "scenic", "presidential range"],
      coordinates: { lat: 44.2573, lng: -71.4411 },
      metadata: { vertical_drop: "1500 ft", annual_snowfall: "200 inches", lifts: "10" },
      isFeatured: false,
    },

    {
      type: "watersports",
      name: "Colorado River - Grand Canyon",
      location: "Lees Ferry, AZ",
      state: "Arizona",
      description: "The ultimate whitewater rafting adventure through 277 miles of the Grand Canyon. Multi-day trips through massive rapids, hidden slot canyons, and ancient geological formations.",
      image: "/images/cat-watersports.jpg",
      rating: 4.95,
      reviews: 2134,
      difficulty: "Hard to Expert",
      season: "April-October",
      regulations: "NPS permit required via weighted lottery. Commercial trips available. No disposable containers. All waste must be packed out. Group size limits enforced.",
      species: ["Rafting", "Kayaking"],
      amenities: ["Commercial Outfitters", "Designated Camps", "Boat Ramps", "Emergency Evacuation Points"],
      tags: ["whitewater", "multi-day", "grand canyon", "bucket list"],
      coordinates: { lat: 36.8653, lng: -111.5876 },
      metadata: { water_type: "whitewater river", flow_rate: "8000-25000 cfs", put_in_takeout: "Lees Ferry to Diamond Creek" },
      isFeatured: true,
    },
    {
      type: "watersports",
      name: "Apostle Islands Sea Caves",
      location: "Bayfield, WI",
      state: "Wisconsin",
      description: "Paddle through spectacular sandstone sea caves carved by Lake Superior waves. Stunning red and orange rock formations, arches, and grottos accessible only by kayak or boat.",
      image: "/images/cat-watersports.jpg",
      rating: 4.85,
      reviews: 1876,
      difficulty: "Moderate",
      season: "June-September",
      regulations: "National Lakeshore regulations apply. Check lake conditions before launching. PFDs required. Commercial guide recommended for inexperienced paddlers. No camping in sea caves.",
      species: ["Kayaking", "SUP"],
      amenities: ["Kayak Rentals", "Guide Services", "Campgrounds", "Visitor Center", "Boat Tours"],
      tags: ["sea caves", "lake superior", "kayaking", "scenic"],
      coordinates: { lat: 46.9200, lng: -90.6600 },
      metadata: { water_type: "great lake", flow_rate: "variable lake conditions", put_in_takeout: "Meyers Beach to sea caves" },
      isFeatured: true,
    },
    {
      type: "watersports",
      name: "Nantahala River",
      location: "Bryson City, NC",
      state: "North Carolina",
      description: "Premier family-friendly whitewater river in the Smoky Mountains with consistent Class II-III rapids fed by dam-controlled releases. Perfect introduction to whitewater in a beautiful forested gorge.",
      image: "/images/cat-watersports.jpg",
      rating: 4.7,
      reviews: 3456,
      difficulty: "Easy to Moderate",
      season: "April-October",
      regulations: "PFDs required for all paddlers. Commercial outfitters recommended for beginners. Stay clear of Nantahala Falls until confident. Helmet recommended for kayakers.",
      species: ["Rafting", "Kayaking", "SUP"],
      amenities: ["Commercial Outfitters", "Boat Rentals", "Campgrounds", "Restaurants", "Changing Rooms"],
      tags: ["family friendly", "whitewater", "beginner", "smoky mountains"],
      coordinates: { lat: 35.3346, lng: -83.5882 },
      metadata: { water_type: "whitewater river", flow_rate: "dam controlled", put_in_takeout: "Pattons Run to Nantahala Falls" },
      isFeatured: false,
    },
    {
      type: "watersports",
      name: "Lake Powell",
      location: "Page, AZ",
      state: "Utah",
      description: "Massive desert reservoir with 1,960 miles of shoreline, hidden slot canyons, and crystal-clear water. World-class SUP, kayaking, and wakeboarding amid stunning red rock scenery.",
      image: "/images/cat-watersports.jpg",
      rating: 4.75,
      reviews: 2567,
      difficulty: "Easy to Moderate",
      season: "March-November",
      regulations: "NPS Glen Canyon Recreation Area fee required. Boat registration required. No wake zones enforced. Portable toilet required for overnight canyon camping.",
      species: ["SUP", "Kayaking", "Wakeboarding", "Jet Skiing"],
      amenities: ["Marinas", "Boat Rentals", "Campgrounds", "Houseboat Rentals", "Restaurants", "Fuel Docks"],
      tags: ["desert lake", "slot canyons", "houseboating", "scenic"],
      coordinates: { lat: 37.0683, lng: -111.2433 },
      metadata: { water_type: "reservoir", flow_rate: "flat water", put_in_takeout: "multiple marinas and ramps" },
      isFeatured: false,
    },
    {
      type: "watersports",
      name: "Columbia River Gorge",
      location: "Hood River, OR",
      state: "Oregon",
      description: "World-renowned wind and kiteboarding destination where strong thermal winds funnel through the dramatic river gorge. Also excellent for SUP, kayaking, and surfing river waves.",
      image: "/images/cat-watersports.jpg",
      rating: 4.8,
      reviews: 1987,
      difficulty: "Moderate to Hard",
      season: "May-September",
      regulations: "PFDs required for all water users. Kiteboarding launch areas designated. Wind advisory warnings posted. Commercial barge traffic has right of way.",
      species: ["Kiteboarding", "Windsurfing", "SUP", "Kayaking"],
      amenities: ["Launch Sites", "Gear Shops", "Lessons", "Campgrounds", "Breweries", "Restaurants"],
      tags: ["wind sports", "kiteboarding", "river gorge", "world class"],
      coordinates: { lat: 45.7185, lng: -121.5137 },
      metadata: { water_type: "river", flow_rate: "strong current with thermal winds", put_in_takeout: "multiple launch sites Hood River to The Dalles" },
      isFeatured: false,
    },

    {
      type: "charters",
      name: "Key West Deep Sea Charters",
      location: "Key West, FL",
      state: "Florida",
      description: "Year-round deep sea fishing in the warm Gulf Stream waters off Key West. Target billfish, tuna, and mahi-mahi with experienced captains who know the legendary fishing grounds of the Florida Keys.",
      image: "/images/cat-charters.jpg",
      rating: 4.8,
      reviews: 2345,
      difficulty: "Easy to Moderate",
      season: "Year-round",
      regulations: "FL saltwater fishing license included with charter. Federal permits for HMS species. Catch limits vary by species. Release required for certain billfish.",
      species: ["Blue Marlin", "Yellowfin Tuna", "Mahi-Mahi", "Sailfish", "Wahoo"],
      amenities: ["Full-Day Charters", "Half-Day Trips", "Equipment Provided", "Fish Cleaning", "Ice Included"],
      tags: ["deep sea", "billfish", "offshore", "tropical"],
      coordinates: { lat: 24.5551, lng: -81.7800 },
      metadata: { charter_type: "offshore", boat_size: "38-65 ft", max_passengers: "6" },
      isFeatured: true,
    },
    {
      type: "charters",
      name: "Outer Banks Inshore Charters",
      location: "Hatteras, NC",
      state: "North Carolina",
      description: "Fish the legendary waters where the Gulf Stream meets the Labrador Current off Cape Hatteras. Incredible diversity of species in the Graveyard of the Atlantic with world-class blue marlin fishing.",
      image: "/images/cat-charters.jpg",
      rating: 4.75,
      reviews: 1876,
      difficulty: "Easy",
      season: "March-November",
      regulations: "NC saltwater fishing license required for inshore. Federal permits for offshore species. Slot limits on red drum. Charter captain handles permits.",
      species: ["Red Drum", "Speckled Trout", "Flounder", "Cobia", "Blue Marlin"],
      amenities: ["Half-Day Trips", "Full-Day Charters", "Equipment Provided", "Fish Cleaning", "Bait Included"],
      tags: ["inshore", "sound fishing", "light tackle", "diverse species"],
      coordinates: { lat: 35.2246, lng: -75.6344 },
      metadata: { charter_type: "inshore and offshore", boat_size: "22-58 ft", max_passengers: "6" },
      isFeatured: true,
    },
    {
      type: "charters",
      name: "Kona Sportfishing Charters",
      location: "Kailua-Kona, HI",
      state: "Hawaii",
      description: "Fish the deep blue waters of the Kona Coast where 1,000-foot depths lie within a mile of shore. World capital of Pacific blue marlin fishing with year-round warm water action.",
      image: "/images/cat-charters.jpg",
      rating: 4.85,
      reviews: 1654,
      difficulty: "Easy to Moderate",
      season: "Year-round, best July-September for marlin",
      regulations: "HI fishing license not required for charter fishing. IPHC regulations for billfish. Tag and release encouraged for marlin. Federal marine sanctuary rules apply.",
      species: ["Pacific Blue Marlin", "Yellowfin Tuna", "Ono", "Mahi-Mahi", "Striped Marlin"],
      amenities: ["Half-Day Charters", "Full-Day Trips", "Tournament Packages", "Equipment Provided", "Fish Processing"],
      tags: ["marlin capital", "deep sea", "tropical", "world class"],
      coordinates: { lat: 19.6400, lng: -155.9969 },
      metadata: { charter_type: "offshore", boat_size: "31-53 ft", max_passengers: "6" },
      isFeatured: false,
    },
    {
      type: "charters",
      name: "Montauk Fishing Charters",
      location: "Montauk, NY",
      state: "New York",
      description: "The Fishing Capital of the World at the eastern tip of Long Island. Incredible striped bass, fluke, and shark fishing with easy access to productive nearshore and offshore grounds.",
      image: "/images/cat-charters.jpg",
      rating: 4.7,
      reviews: 2134,
      difficulty: "Easy",
      season: "April-November",
      regulations: "NY marine fishing license required. Striped bass slot limits enforced. Shark fishing catch and release for most species. Federal HMS permit for tuna.",
      species: ["Striped Bass", "Fluke", "Bluefin Tuna", "Mako Shark", "Bluefish"],
      amenities: ["Half-Day Trips", "Full-Day Charters", "Night Trips", "Equipment Provided", "Fish Cleaning"],
      tags: ["striped bass", "nearshore", "shark fishing", "montauk"],
      coordinates: { lat: 41.0357, lng: -71.9545 },
      metadata: { charter_type: "nearshore and offshore", boat_size: "25-50 ft", max_passengers: "6" },
      isFeatured: false,
    },
    {
      type: "charters",
      name: "Destin Charter Fleet",
      location: "Destin, FL",
      state: "Florida",
      description: "The World's Luckiest Fishing Village with one of the largest charter fleets in the country. Easy access to productive Gulf waters with red snapper, grouper, and pelagic species.",
      image: "/images/cat-charters.jpg",
      rating: 4.65,
      reviews: 3210,
      difficulty: "Easy",
      season: "Year-round, best spring and fall",
      regulations: "FL saltwater fishing license included with charter. Red snapper season limited. Federal reef fish permits required. Daily bag limits strictly enforced.",
      species: ["Red Snapper", "Grouper", "King Mackerel", "Cobia", "Amberjack"],
      amenities: ["Half-Day Trips", "Full-Day Charters", "Party Boats", "Equipment Provided", "Fish Cleaning", "Dock Access"],
      tags: ["gulf fishing", "bottom fishing", "family friendly", "party boats"],
      coordinates: { lat: 30.3935, lng: -86.4958 },
      metadata: { charter_type: "nearshore and offshore", boat_size: "24-65 ft", max_passengers: "6-20" },
      isFeatured: false,
    },
  ]);

  console.log("Activity locations seeded successfully!");
}

import { seedCatalogLocations } from "./catalog-seed";
import { seedTennesseeCatalog } from "./tennessee-catalog-seed";
import { eq } from "drizzle-orm";

async function seedEcosystemMembers() {
  console.log("Checking ecosystem members...");

  const ecosystemMembers = [
    {
      firstName: "Kathy",
      lastName: "Nguyen",
      email: "kathy@happyeats.io",
      password: "HappyEats@2025",
      pin: "7724",
      trustLayerId: "tl-kathy-he01",
      ecosystemApp: "Happy Eats",
      tier: "Outdoor Explorer",
    },
    {
      firstName: "Marcus",
      lastName: "Chen",
      email: "marcus@trusthome.io",
      password: "TrustHome@2025",
      pin: "4419",
      trustLayerId: "tl-marc-th01",
      ecosystemApp: "TrustHome",
      tier: "Free Explorer",
    },
    {
      firstName: "Devon",
      lastName: "Park",
      email: "devon@signal.dw",
      password: "Signal@2025",
      pin: "8832",
      trustLayerId: "tl-devn-sg01",
      ecosystemApp: "Signal",
      tier: "Free Explorer",
    },
  ];

  for (const member of ecosystemMembers) {
    const [existing] = await db.select().from(users).where(eq(users.email, member.email)).limit(1);
    if (existing) {
      if (!existing.ecosystemPinHash && member.pin) {
        const pinHash = await bcrypt.hash(member.pin, 12);
        await db.update(users).set({
          ecosystemPinHash: pinHash,
          ecosystemApp: member.ecosystemApp,
          trustLayerId: existing.trustLayerId || member.trustLayerId,
        }).where(eq(users.id, existing.id));
        console.log(`  Updated ${member.email} with ecosystem PIN`);
      }
      continue;
    }

    const passwordHash = await bcrypt.hash(member.password, 12);
    const pinHash = await bcrypt.hash(member.pin, 12);

    await db.insert(users).values({
      firstName: member.firstName,
      lastName: member.lastName,
      email: member.email,
      passwordHash,
      emailVerified: true,
      tier: member.tier,
      trustLayerId: member.trustLayerId,
      ecosystemPinHash: pinHash,
      ecosystemApp: member.ecosystemApp,
    });
    console.log(`  Created ecosystem member: ${member.firstName} ${member.lastName} (${member.ecosystemApp})`);
  }

  console.log("Ecosystem members seeded!");
}

export async function runAllSeeds() {
  try {
    await seed();
    await seedActivityLocations();
    await seedCatalogLocations();
    await seedTennesseeCatalog();
    await seedEcosystemMembers();
    console.log("All seeding complete!");
  } catch (err) {
    console.error("Seed error:", err);
  }
}

const isDirectRun = process.argv[1]?.endsWith("seed.ts") || process.argv[1]?.endsWith("seed.js");
if (isDirectRun) {
  runAllSeeds().then(() => process.exit(0)).catch(() => process.exit(1));
}
